import 'package:flutter/material.dart';
import 'package:flutterapp/flutdemoapp/generatedframe2widget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/flutdemoapp/generatedframe2widget/generated/GeneratedRectangle3Widget.dart';

/* Frame Frame 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 248, 225, 20),
                ),
              ),
              Positioned(
                left: 23.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 62.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 219.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 62.0,
                child: GeneratedRectangle4Widget(),
              )
            ]),
      ),
    ));
  }
}
