name: cat_zika
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  auto_size_text: 3.0.0
  cached_network_image: 3.1.0+1
  chewie: 1.2.2
  collection: 1.15.0
  emoji_flag_converter: 1.1.0
  fl_chart: 0.50.6
  flutter_credit_card: 2.0.0
  flutter_google_places: 0.3.0
  font_awesome_flutter: 10.1.0
  google_api_headers:
  google_fonts: 2.2.0
  google_maps_flutter: 2.1.1
  google_maps_webservice:
  internet_file: 1.0.0+2
  intl: 0.17.0
  json_path: 0.3.1
  json_serializable: 6.1.3
  mapbox_search: 3.0.1+2
  mime_type: 1.0.0
  page_transition: 2.0.4
  pdfx: 2.0.1+2
  rive: 0.7.33
  rxdart: 0.26.0
  shared_preferences: 2.0.11
  table_calendar: 3.0.5
  timeago: 3.1.0
  url_launcher: 6.0.15
  video_player: 2.2.7
  webviewx: 0.2.1
  youtube_plyr_iframe: 2.0.7

  # For assets_audio_player
  uuid: ^3.0.5
  http: ^0.13.4 # to download / cache network files
  path_provider: ^2.0.8 # removed this because it cancel flutter/android/ios on pub.dev path_provider: ^1.6.10

  # For flutter_html
  html: '>=0.15.0 <1.0.0'
  csslib: '>=0.17.0 <1.0.0'
  flutter_layout_grid: '>=1.0.1 <2.0.0'
  webview_flutter: '>=2.0.4 <3.0.0'
  chewie_audio: '>=1.2.0 <2.0.0'
  flutter_svg: '>=0.22.0 <1.0.0'
  numerus: '>=1.1.1 <2.0.0'

  cupertino_icons: ^1.0.2

dependency_overrides:
  collection: ^1.16.0
  
dev_dependencies:
  dependency_validator:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

