name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/designs/images/auto-group-4yup.png
    - assets/designs/images/auto-group-xcht.png
    - assets/designs/images/color.png
    - assets/designs/images/auto-group-txuv.png
    - assets/designs/images/cloth2.png
    - assets/designs/images/icon-chevron-down.png
    - assets/designs/images/group-11.png
    - assets/designs/images/eyes.png
    - assets/designs/images/auto-group-ufpy.png
    - assets/designs/images/bx-sort-1.png
    - assets/designs/images/auto-group-ctzr.png
    - assets/designs/images/combined-shape-4NH.png
    - assets/designs/images/group-11-As7.png
    - assets/designs/images/combined-shape.png
    - assets/designs/images/shadows-bg.png
    - assets/designs/images/hair.png
    - assets/designs/images/group-19.png
    - assets/designs/images/background-primary-bg.png
    - assets/designs/images/icon-chevron-left.png
    - assets/designs/images/download-alt-1.png
    - assets/designs/images/user-fill-1.png
    - assets/designs/images/ellipse-7.png
    - assets/designs/images/auto-group-haiy.png
    - assets/designs/images/lips.png
    - assets/designs/images/icon-chevron-left-bQH.png
    - assets/designs/images/group-11-hi5.png
    - assets/designs/images/auto-group-zlv3.png
    - assets/designs/images/group-2.png
    - assets/designs/images/icon-calendar.png
    - assets/designs/images/background-primary-bg-kPP.png
    - assets/designs/images/.png
    - assets/designs/images/pants2.png
    - assets/designs/images/delete.png
    - assets/designs/images/bg-arrow-up-bg.png
    - assets/designs/images/group-8.png
    - assets/designs/images/vector-2.png
    - assets/designs/images/image-15.png
    - assets/designs/images/rectangle-16.png
    - assets/designs/images/background-primary-bg-zCV.png
    - assets/designs/images/shoes.png
    - assets/designs/images/pink-donut-bg.png
    - assets/designs/images/ring-bg.png
    - assets/designs/images/blue-donut-bg.png
    - assets/designs/images/background-primary-bg-4Lm.png
    - assets/designs/images/arrow-down-bg.png
    - assets/designs/images/frame-5.png
    - assets/designs/images/combined-shape-iN1.png
    - assets/designs/images/icon-plus-circle.png
    - assets/designs/images/battery.png
    - assets/designs/images/home-1.png
    - assets/designs/images/ellipse-8.png
    - assets/designs/images/combined-shape-W9K.png
    - assets/designs/images/frame-7.png
    - assets/designs/images/background-primary-bg-wnm.png
    - assets/designs/images/group-16.png
    - assets/designs/images/vector-1.png
    - assets/designs/images/user-fill-1-9YZ.png
    - assets/designs/images/shield-checkered-fill-1.png
    - assets/designs/images/image-6.png
    - assets/designs/images/combined-shape-Dm7.png
    - assets/designs/images/battery-K9F.png
    - assets/designs/images/combined-shape-h5o.png
    - assets/designs/images/wallet-1.png
    - assets/designs/images/auto-group-mtg9.png
    - assets/designs/images/blur-behind.png
    - assets/designs/images/auto-group-cdfk.png
    - assets/designs/images/dollar-bg.png
    - assets/designs/images/group-14.png
    - assets/designs/images/group-6.png
    - assets/designs/images/combined-shape-EYu.png
    - assets/designs/images/background-primary-bg-ncD.png
    - assets/designs/images/background-primary-bg-VFj.png
    - assets/designs/images/bg-dollar-bg.png
    - assets/designs/images/wallet-1-fJd.png
    - assets/designs/images/lock-key-fill-1.png
    - assets/designs/images/rectangle-9.png
    - assets/designs/images/auto-group-8u2m.png
    - assets/designs/images/orange-donut-bg.png
    - assets/designs/images/battery-Skd.png
    - assets/designs/images/group-13.png
    - assets/designs/images/background-primary-bg-68u.png
    - assets/designs/images/color-nnR.png
    - assets/designs/images/glasses.png
    - assets/designs/images/icon-chevron-left-PjK.png
    - assets/designs/images/frame-4.png
    - assets/designs/images/bar-chart-1.png
    - assets/designs/images/arrow-up-bg.png
    - assets/designs/images/background-primary-bg-Gk5.png
    - assets/designs/images/group-12.png
    - assets/designs/images/rectangle-9-oc9.png
    - assets/designs/images/group-18.png
    - assets/designs/images/pants.png
    - assets/designs/images/home-1-cFw.png
    - assets/designs/images/combined-shape-MiD.png
    - assets/designs/images/bar-chart-1-o6M.png
    - assets/designs/images/image-14.png
    - assets/designs/images/group-15.png
    - assets/designs/images/cloth.png
    - assets/designs/images/image-13.png
    - assets/designs/images/envelope-simple-fill-1.png
    - assets/designs/images/purple-donut-bg.png
    - assets/designs/images/icon-chevron-down-4Sq.png
    - assets/designs/images/bg-arrow-down-bg.png
    - assets/designs/images/icon-chevron-down-1V7.png
    - assets/designs/images/bar-chart-fill-1.png
    - assets/designs/images/auto-group-teqb.png
    - assets/designs/images/image-5.png
    - assets/designs/images/frame-4-BXs.png
    - assets/designs/images/skin.png
    - assets/designs/images/auto-group-zahj.png
    - assets/designs/images/frame-4-CmT.png
    - assets/designs/images/group-6-SLM.png
    - assets/designs/images/image-6-2uT.png
    - assets/designs/images/user-1-1.png
    - assets/designs/images/battery-MvM.png
    - assets/designs/images/base-bg.png
    - assets/designs/images/specular.png
    - assets/designs/images/group-11-8S1.png
    - assets/designs/images/rectangle-9-sU9.png
    - assets/designs/images/users-fill-1.png
    - assets/designs/images/icon-chevron-left-5Fb.png
    - assets/designs/images/frame-21.png
    - assets/designs/images/group-6-u7K.png
    - assets/designs/images/battery-EVs.png
    - assets/designs/images/home-1-yYR.png
    - assets/designs/images/rectangle.png
    - assets/designs/images/frame-21-7NV.png
    - assets/designs/images/image-6-wMo.png
    - assets/designs/images/rectangle-9-vEq.png
    - assets/designs/images/combined-shape-H2m.png
    - assets/designs/images/image-5-9kR.png
    - assets/designs/images/frame-4-hNu.png
    - assets/designs/images/user-1-1-weV.png
    - assets/designs/images/combined-shape-bzu.png
    - assets/designs/images/frame-21-mTT.png
    - assets/designs/images/home-1-ZGq.png
    - assets/designs/images/image-13-wWd.png
    - assets/designs/images/user-1-1-dfK.png
    - assets/designs/images/wallet-fill.png
    - assets/designs/images/visa.png
    - assets/designs/images/image-6-xH3.png
    - assets/designs/images/bar-chart-1-3UH.png
    - assets/designs/images/battery-qEV.png
    - assets/designs/images/image-16.png
    - assets/designs/images/combined-shape-waD.png
    - assets/designs/images/shape.png
    - assets/designs/images/wallet-fill-h41.png
    - assets/designs/images/decorativeline.png
    - assets/designs/images/icon-chevron-left-XWD.png
    - assets/designs/images/user-1-1-v6R.png
    - assets/designs/images/frame-9.png
    - assets/designs/images/rectangle-9-WZ3.png
    - assets/designs/images/combined-shape-89b.png
    - assets/designs/images/frame-21-Qxu.png
    - assets/designs/images/frame-9-HWu.png
    - assets/designs/images/combined-shape-YU5.png
    - assets/designs/images/bar-chart-1-XjK.png
    - assets/designs/images/rectangle-9-8y3.png
    - assets/designs/images/frame-21-k9b.png
    - assets/designs/images/decorativeline-3ZF.png
    - assets/designs/images/group-6-HTb.png
    - assets/designs/images/emv-chip.png
    - assets/designs/images/battery-AtV.png
    - assets/designs/images/frame-4-AsP.png
    - assets/designs/images/emv-chip-YN9.png
    - assets/designs/images/combined-shape-nXP.png
    - assets/designs/images/group-6-GhT.png
    - assets/designs/images/user-1-1-z8d.png
    - assets/designs/images/rectangle-9-Byo.png
    - assets/designs/images/frame-21-p13.png
    - assets/designs/images/icon-chevron-left-cdb.png
    - assets/designs/images/glossy.png
    - assets/designs/images/icon-chevron-left-Q5j.png
    - assets/designs/images/wallet-fill-ccM.png
    - assets/designs/images/wallet-fill-WBw.png
    - assets/designs/images/group-6-QZK.png
    - assets/designs/images/form-bg.png
    - assets/designs/images/combined-shape-Lry.png
    - assets/designs/images/bank-fill-1.png
    - assets/designs/images/logo-paypal-1.png
    - assets/designs/images/frame-4-78h.png
    - assets/designs/images/battery-5DP.png
    - assets/designs/images/battery-PUq.png
    - assets/designs/images/icon-chevron-left-MbB.png
    - assets/designs/images/wallet-fill-WRT.png
    - assets/designs/images/combined-shape-cAy.png
    - assets/designs/images/home-1-t6R.png
    - assets/designs/images/bar-chart-1-qDo.png
    - assets/designs/images/icon-chevron-up.png
    - assets/designs/images/currency-circle-dollar-fill-1.png
    - assets/designs/images/rectangle-9-KLH.png
    - assets/designs/images/home-1-5bb.png
    - assets/designs/images/group-6-arR.png
    - assets/designs/images/bar-chart-1-QoP.png
    - assets/designs/images/group-19-U3f.png
    - assets/designs/images/user-1-1-AhB.png
    - assets/designs/images/check-circle-fill-1.png
    - assets/designs/images/home-1-WVT.png
    - assets/designs/images/icon-chevron-left-Kyo.png
    - assets/designs/images/combined-shape-WqK.png
    - assets/designs/images/image-13-aih.png
    - assets/designs/images/rectangle-jSu.png
    - assets/designs/images/group-6-4xM.png
    - assets/designs/images/bar-chart-1-5gh.png
    - assets/designs/images/wallet-fill-egD.png
    - assets/designs/images/icon-chevron-up-ckm.png
    - assets/designs/images/user-1-1-5iD.png
    - assets/designs/images/combined-shape-M25.png
    - assets/designs/images/combined-shape-3yf.png
    - assets/designs/images/home-1-cbw.png
    - assets/designs/images/combined-shape-jSu.png
    - assets/designs/images/rectangle-5U9.png
    - assets/designs/images/group-19-m2d.png
    - assets/designs/images/group-11-fmX.png
    - assets/designs/images/battery-jRF.png
    - assets/designs/images/combined-shape-Uhs.png
    - assets/designs/images/rectangle-9-EYu.png
    - assets/designs/images/group-6-te1.png
    - assets/designs/images/group-24.png
    - assets/designs/images/group-23.png
    - assets/designs/images/icon-chevron-left-BEd.png
    - assets/designs/images/combined-shape-qru.png
    - assets/designs/images/logo-paypal-1-EpV.png
    - assets/designs/images/credit-card-fill-1.png
    - assets/designs/images/image-6-m6u.png
    - assets/designs/images/group-19-cfo.png
    - assets/designs/images/rectangle-9-5Q9.png
    - assets/designs/images/battery-E6R.png
    - assets/designs/images/home-1-TBT.png
    - assets/designs/images/bar-chart-1-tLd.png
    - assets/designs/images/battery-zeZ.png
    - assets/designs/images/user-1-1-v6q.png
    - assets/designs/images/wallet-fill-1ZX.png
    - assets/designs/images/combined-shape-vf7.png
    - assets/designs/images/group-6-thj.png
    - assets/designs/images/user-1-1-SCm.png
    - assets/designs/images/icon-chevron-left-Z8h.png
    - assets/designs/images/image-6-cGd.png
    - assets/designs/images/group-19-mQy.png
    - assets/designs/images/home-1-qRP.png
    - assets/designs/images/bar-chart-1-4E1.png
    - assets/designs/images/combined-shape-FF3.png
    - assets/designs/images/wallet-fill-FBT.png
    - assets/designs/images/check-circle-fill-1-zms.png
    - assets/designs/images/icon-chevron-up-BCH.png
    - assets/designs/images/rectangle-9-3eu.png
    - assets/designs/images/group-6-Kxh.png
    - assets/designs/images/copy-simple-fill-1.png
    - assets/designs/images/bar-chart-1-yzm.png
    - assets/designs/images/combined-shape-NbP.png
    - assets/designs/images/user-1-1-ngV.png
    - assets/designs/images/battery-Kuo.png
    - assets/designs/images/rectangle-9-7rd.png
    - assets/designs/images/icon-chevron-left-ELu.png
    - assets/designs/images/home-1-LCu.png
    - assets/designs/images/combined-shape-oU1.png
    - assets/designs/images/group-19-Vzu.png
    - assets/designs/images/wallet-fill-zQV.png
    - assets/thumbnail/images/screen-1.png
    - assets/thumbnail/images/screen-2.png
    - assets/thumbnail/images/screen-3.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
