// ignore_for_file: file_names
import 'package:flutter/material.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedGraphicDesignMasterWidget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/Generated28KMembersWidget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/Generated16MinutesWidget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedSaly20Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedSaly25Widget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/Generated10MinutesWidget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedSaly21Widget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedEllipse6Widget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/Generated12MinutesWidget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedSaly36Widget2.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedFrame6Widget1.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedRectangle1Widget3.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedFreeWidget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedMaskGroupWidget2.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedFundamentalofDesignWidget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedLayoutDesignWidget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedIntroductionDesignGraphicWidget.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedFrameWidget17.dart';
import 'package:flutterapp/figmaflutterapp/generateddetailswidget/generated/GeneratedRectangle13Widget.dart';

/* Frame Details
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDetailsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(fit: StackFit.expand, alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 41, 39, 79),
                ),
              ),
              Positioned(
                left: -2.0,
                top: -24.0,
                right: null,
                bottom: null,
                width: 416.0,
                height: 392.0,
                child: GeneratedRectangle1Widget3(),
              ),
              Positioned(
                left: 168.0,
                top: 21.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 349.0,
                child: GeneratedMaskGroupWidget2(),
              ),
              Positioned(
                left: 473.0,
                top: -24.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 414.0,
                child: GeneratedSaly36Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6256038647342995;

                  final double height =
                      constraints.maxHeight * 0.03459821428571429;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.04830917874396135,
                        y: constraints.maxHeight * 0.46763392857142855,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGraphicDesignMasterWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 20.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 18.0,
                child: GeneratedFrame6Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedEllipse3Widget(),
              ),
              Positioned(
                left: 44.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedEllipse4Widget(),
              ),
              Positioned(
                left: 68.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedEllipse5Widget(),
              ),
              Positioned(
                left: 92.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedEllipse6Widget(),
              ),
              Positioned(
                left: 149.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 23.0,
                child: Generated28KMembersWidget(),
              ),
              Positioned(
                left: 325.0,
                top: 474.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 47.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 340.0,
                top: 486.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFrameWidget17(),
              ),
              Positioned(
                left: 20.0,
                top: 573.0,
                right: null,
                bottom: null,
                width: 374.0,
                height: 82.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 667.0,
                right: null,
                bottom: null,
                width: 374.0,
                height: 82.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 761.0,
                right: null,
                bottom: null,
                width: 374.0,
                height: 82.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 573.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 82.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 667.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 82.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 761.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 82.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 551.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 130.0,
                child: GeneratedSaly20Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5531400966183575;

                  final double height =
                      constraints.maxHeight * 0.025669642857142856;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3164251207729469,
                        y: constraints.maxHeight * 0.6607142857142857,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedIntroductionDesignGraphicWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.45652173913043476;

                  final double height =
                      constraints.maxHeight * 0.025669642857142856;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3164251207729469,
                        y: constraints.maxHeight * 0.765625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFundamentalofDesignWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2826086956521739;

                  final double height =
                      constraints.maxHeight * 0.025669642857142856;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3164251207729469,
                        y: constraints.maxHeight * 0.8705357142857143,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedLayoutDesignWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.17391304347826086;

                  final double height =
                      constraints.maxHeight * 0.020089285714285716;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3140096618357488,
                        y: constraints.maxHeight * 0.6908482142857143,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated12MinutesWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.17391304347826086;

                  final double height =
                      constraints.maxHeight * 0.020089285714285716;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3140096618357488,
                        y: constraints.maxHeight * 0.7957589285714286,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated16MinutesWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.17391304347826086;

                  final double height =
                      constraints.maxHeight * 0.020089285714285716;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3140096618357488,
                        y: constraints.maxHeight * 0.9006696428571429,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated10MinutesWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 212.0,
                top: 619.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 20.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06521739130434782;

                  final double height =
                      constraints.maxHeight * 0.020089285714285716;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.533816425120773,
                        y: constraints.maxHeight * 0.6953125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreeWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 10.0,
                top: 770.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 62.0,
                child: GeneratedSaly25Widget(),
              ),
              Positioned(
                left: -2.0,
                top: 647.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 133.0,
                child: GeneratedSaly21Widget(),
              )
            ]),
      ),
    ));
  }
}
