name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/designs/images/color.png
    - assets/designs/images/combined-shape.png
    - assets/designs/images/frame-5.png
    - assets/designs/images/group-16.png
    - assets/designs/images/hair.png
    - assets/designs/images/auto-group-mtg9.png
    - assets/designs/images/home-1.png
    - assets/designs/images/ellipse-7.png
    - assets/designs/images/image-5.png
    - assets/designs/images/group-11.png
    - assets/designs/images/pants2.png
    - assets/designs/images/auto-group-zlv3.png
    - assets/designs/images/cloth.png
    - assets/designs/images/pants.png
    - assets/designs/images/icon-chevron-down.png
    - assets/designs/images/group-14.png
    - assets/designs/images/auto-group-8u2m.png
    - assets/designs/images/eyes.png
    - assets/designs/images/auto-group-ufpy.png
    - assets/designs/images/skin.png
    - assets/designs/images/arrow-up-bg.png
    - assets/designs/images/combined-shape-BsB.png
    - assets/designs/images/group-12.png
    - assets/designs/images/lips.png
    - assets/designs/images/cloth2.png
    - assets/designs/images/auto-group-4yup.png
    - assets/designs/images/shadows-bg.png
    - assets/designs/images/group-13.png
    - assets/designs/images/blue-donut-bg.png
    - assets/designs/images/pink-donut-bg.png
    - assets/designs/images/image-15.png
    - assets/designs/images/auto-group-haiy.png
    - assets/designs/images/download-alt-1.png
    - assets/designs/images/purple-donut-bg.png
    - assets/designs/images/auto-group-xcht.png
    - assets/designs/images/auto-group-teqb.png
    - assets/designs/images/bx-sort-1.png
    - assets/designs/images/group-8.png
    - assets/designs/images/vector-1.png
    - assets/designs/images/bg-dollar-bg.png
    - assets/designs/images/ellipse-8.png
    - assets/designs/images/group-11-R4Z.png
    - assets/designs/images/user-1-1.png
    - assets/designs/images/ring-bg.png
    - assets/designs/images/glasses.png
    - assets/designs/images/bg-arrow-down-bg.png
    - assets/designs/images/auto-group-ctzr.png
    - assets/designs/images/frame-7.png
    - assets/designs/images/icon-chevron-down-vYd.png
    - assets/designs/images/auto-group-zahj.png
    - assets/designs/images/battery.png
    - assets/designs/images/background-primary-bg.png
    - assets/designs/images/shoes.png
    - assets/designs/images/background-primary-bg-2kd.png
    - assets/designs/images/group-11-e1s.png
    - assets/designs/images/icon-chevron-left.png
    - assets/designs/images/group-2.png
    - assets/designs/images/arrow-down-bg.png
    - assets/designs/images/blur-behind.png
    - assets/designs/images/background-primary-bg-MdP.png
    - assets/designs/images/orange-donut-bg.png
    - assets/designs/images/bar-chart-fill-1.png
    - assets/designs/images/frame-4.png
    - assets/designs/images/icon-calendar.png
    - assets/designs/images/home-1-QbF.png
    - assets/designs/images/combined-shape-2xd.png
    - assets/designs/images/group-15.png
    - assets/designs/images/rectangle-16.png
    - assets/designs/images/combined-shape-Qaq.png
    - assets/designs/images/auto-group-txuv.png
    - assets/designs/images/icon-chevron-left-nwf.png
    - assets/designs/images/vector-2.png
    - assets/designs/images/group-11-bt1.png
    - assets/designs/images/icon-chevron-down-2VK.png
    - assets/designs/images/group-6.png
    - assets/designs/images/image-5-853.png
    - assets/designs/images/background-primary-bg-xXF.png
    - assets/designs/images/shield-checkered-fill-1.png
    - assets/designs/images/specular.png
    - assets/designs/images/battery-upq.png
    - assets/designs/images/combined-shape-Bhw.png
    - assets/designs/images/combined-shape-Aow.png
    - assets/designs/images/lock-key-fill-1.png
    - assets/designs/images/group-19.png
    - assets/designs/images/color-Jay.png
    - assets/designs/images/background-primary-bg-zpV.png
    - assets/designs/images/background-primary-bg-Fho.png
    - assets/designs/images/bar-chart-1.png
    - assets/designs/images/combined-shape-5nm.png
    - assets/designs/images/wallet-1.png
    - assets/designs/images/battery-bCR.png
    - assets/designs/images/background-primary-bg-zGm.png
    - assets/designs/images/.png
    - assets/designs/images/frame-21.png
    - assets/designs/images/rectangle.png
    - assets/designs/images/image-14.png
    - assets/designs/images/user-1-1-Yzh.png
    - assets/designs/images/icon-chevron-left-S6R.png
    - assets/designs/images/background-primary-bg-Kdw.png
    - assets/designs/images/frame-9.png
    - assets/designs/images/user-fill-1.png
    - assets/designs/images/image-6.png
    - assets/designs/images/image-6-JYD.png
    - assets/designs/images/image-6-9am.png
    - assets/designs/images/image-6-smf.png
    - assets/designs/images/dollar-bg.png
    - assets/designs/images/auto-group-cdfk.png
    - assets/designs/images/group-6-vEy.png
    - assets/designs/images/rectangle-9.png
    - assets/designs/images/battery-t2Z.png
    - assets/designs/images/frame-4-uHf.png
    - assets/designs/images/bg-arrow-up-bg.png
    - assets/designs/images/frame-4-ZvV.png
    - assets/designs/images/users-fill-1.png
    - assets/designs/images/combined-shape-6HK.png
    - assets/designs/images/bar-chart-1-SPf.png
    - assets/designs/images/frame-21-Pim.png
    - assets/designs/images/group-6-JNR.png
    - assets/designs/images/combined-shape-sZ7.png
    - assets/designs/images/battery-74q.png
    - assets/designs/images/bar-chart-1-1y7.png
    - assets/designs/images/frame-9-qFB.png
    - assets/designs/images/group-6-1hP.png
    - assets/designs/images/envelope-simple-fill-1.png
    - assets/designs/images/background-primary-bg-RVX.png
    - assets/designs/images/icon-chevron-left-9Nm.png
    - assets/designs/images/user-fill-1-Vss.png
    - assets/designs/images/combined-shape-yGh.png
    - assets/designs/images/delete.png
    - assets/designs/images/combined-shape-AMB.png
    - assets/designs/images/base-bg.png
    - assets/designs/images/frame-21-AFw.png
    - assets/designs/images/frame-4-DtR.png
    - assets/designs/images/wallet-fill.png
    - assets/designs/images/frame-21-Jus.png
    - assets/designs/images/icon-chevron-left-wC9.png
    - assets/designs/images/group-18.png
    - assets/designs/images/battery-RSd.png
    - assets/designs/images/wallet-1-Y1T.png
    - assets/designs/images/group-6-9Au.png
    - assets/designs/images/icon-plus-circle.png
    - assets/designs/images/combined-shape-4yj.png
    - assets/designs/images/home-1-e5K.png
    - assets/designs/images/rectangle-9-sYH.png
    - assets/designs/images/frame-21-yrD.png
    - assets/designs/images/user-1-1-4TP.png
    - assets/designs/images/combined-shape-ccM.png
    - assets/designs/images/icon-chevron-left-aM3.png
    - assets/designs/images/user-1-1-zu3.png
    - assets/designs/images/home-1-YTX.png
    - assets/designs/images/combined-shape-rhj.png
    - assets/designs/images/rectangle-9-QQu.png
    - assets/designs/images/emv-chip.png
    - assets/designs/images/decorativeline.png
    - assets/designs/images/home-1-Fnu.png
    - assets/designs/images/combined-shape-dqP.png
    - assets/designs/images/decorativeline-Wnh.png
    - assets/designs/images/frame-21-se5.png
    - assets/designs/images/image-16.png
    - assets/designs/images/visa.png
    - assets/designs/images/battery-DNd.png
    - assets/designs/images/image-13.png
    - assets/designs/images/wallet-fill-MKT.png
    - assets/designs/images/logo-paypal-1.png
    - assets/designs/images/image-13-fPB.png
    - assets/designs/images/bar-chart-1-kPw.png
    - assets/designs/images/wallet-fill-rSy.png
    - assets/designs/images/user-1-1-WUD.png
    - assets/designs/images/home-1-bkZ.png
    - assets/designs/images/emv-chip-S3f.png
    - assets/designs/images/rectangle-9-8Ny.png
    - assets/designs/images/battery-8qB.png
    - assets/designs/images/icon-chevron-left-JLV.png
    - assets/designs/images/group-6-PC9.png
    - assets/designs/images/frame-4-SHB.png
    - assets/designs/images/check-circle-fill-1.png
    - assets/designs/images/currency-circle-dollar-fill-1.png
    - assets/designs/images/combined-shape-1Hf.png
    - assets/designs/images/group-19-MPj.png
    - assets/designs/images/combined-shape-73T.png
    - assets/designs/images/rectangle-9-i1K.png
    - assets/designs/images/frame-4-WTw.png
    - assets/designs/images/user-1-1-L2H.png
    - assets/designs/images/bank-fill-1.png
    - assets/designs/images/home-1-CPF.png
    - assets/designs/images/home-1-2ku.png
    - assets/designs/images/wallet-fill-D7s.png
    - assets/designs/images/combined-shape-3dw.png
    - assets/designs/images/rectangle-9-Eww.png
    - assets/designs/images/image-13-uCq.png
    - assets/designs/images/user-1-1-Lfo.png
    - assets/designs/images/bar-chart-1-vy3.png
    - assets/designs/images/bar-chart-1-ePF.png
    - assets/designs/images/bar-chart-1-msB.png
    - assets/designs/images/icon-chevron-up.png
    - assets/designs/images/group-6-2R3.png
    - assets/designs/images/form-bg.png
    - assets/designs/images/icon-chevron-left-ibw.png
    - assets/designs/images/group-11-dD7.png
    - assets/designs/images/icon-chevron-up-MQ1.png
    - assets/designs/images/wallet-fill-hRf.png
    - assets/designs/images/battery-zvZ.png
    - assets/designs/images/wallet-fill-aNy.png
    - assets/designs/images/icon-chevron-left-cNq.png
    - assets/designs/images/shape.png
    - assets/designs/images/battery-WhB.png
    - assets/designs/images/group-6-whw.png
    - assets/designs/images/combined-shape-xd3.png
    - assets/designs/images/group-19-WTX.png
    - assets/designs/images/rectangle-9-uEm.png
    - assets/designs/images/group-24.png
    - assets/designs/images/image-6-stH.png
    - assets/designs/images/icon-chevron-left-vr9.png
    - assets/designs/images/combined-shape-Wn1.png
    - assets/designs/images/group-19-AiH.png
    - assets/designs/images/user-1-1-FYh.png
    - assets/designs/images/rectangle-7bs.png
    - assets/designs/images/combined-shape-nN9.png
    - assets/designs/images/home-1-TWM.png
    - assets/designs/images/battery-Bfj.png
    - assets/designs/images/credit-card-fill-1.png
    - assets/designs/images/logo-paypal-1-sYR.png
    - assets/designs/images/image-6-LWZ.png
    - assets/designs/images/bar-chart-1-UoP.png
    - assets/designs/images/rectangle-kRs.png
    - assets/designs/images/group-23.png
    - assets/designs/images/wallet-fill-iZ3.png
    - assets/designs/images/group-6-pP7.png
    - assets/designs/images/wallet-fill-r5s.png
    - assets/designs/images/group-19-iZB.png
    - assets/designs/images/combined-shape-wp9.png
    - assets/designs/images/home-1-44m.png
    - assets/designs/images/combined-shape-GwF.png
    - assets/designs/images/battery-e53.png
    - assets/designs/images/combined-shape-V25.png
    - assets/designs/images/copy-simple-fill-1.png
    - assets/designs/images/combined-shape-GKo.png
    - assets/designs/images/rectangle-9-kLD.png
    - assets/designs/images/icon-chevron-left-gZB.png
    - assets/designs/images/user-1-1-2Q5.png
    - assets/designs/images/home-1-UuB.png
    - assets/designs/images/wallet-fill-4Jh.png
    - assets/designs/images/check-circle-fill-1-tjX.png
    - assets/designs/images/icon-chevron-left-Wvy.png
    - assets/designs/images/battery-1id.png
    - assets/designs/images/group-6-sL9.png
    - assets/designs/images/rectangle-9-WK7.png
    - assets/designs/images/user-1-1-oKB.png
    - assets/designs/images/group-6-P4y.png
    - assets/designs/images/group-19-atm.png
    - assets/designs/images/bar-chart-1-37b.png
    - assets/designs/images/icon-chevron-up-3VF.png
    - assets/designs/images/rectangle-9-BLZ.png
    - assets/designs/images/glossy.png
    - assets/designs/images/combined-shape-PDF.png
    - assets/designs/images/bar-chart-1-tQu.png
    - assets/designs/images/rectangle-9-NXF.png
    - assets/designs/images/rectangle-9-9t1.png
    - assets/thumbnail/images/screen-1.png
    - assets/thumbnail/images/screen-2.png
    - assets/thumbnail/images/screen-3.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
