import 'package:flutter/material.dart';
import 'package:flutterapp/figmaflutterapp/generatedhomewidget/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/figmaflutterapp/generatedhomewidget/generated/GeneratedOnlineWidget.dart';
import 'package:flutterapp/figmaflutterapp/generatedhomewidget/generated/GeneratedMasterClassWidget.dart';
import 'package:flutterapp/figmaflutterapp/generatedhomewidget/generated/GeneratedFromover80LecturesWidget.dart';
import 'package:flutterapp/figmaflutterapp/generatedhomewidget/generated/GeneratedFrame5Widget.dart';
import 'package:flutterapp/figmaflutterapp/generatedhomewidget/generated/GeneratedFreeonlineclassWidget.dart';
import 'package:flutterapp/figmaflutterapp/generatedhomewidget/generated/GeneratedFrame4Widget.dart';
import 'package:flutterapp/figmaflutterapp/generatedhomewidget/generated/GeneratedFrame3Widget.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(fit: StackFit.expand, alignment: Alignment.center,
            // overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 41, 39, 79),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 47.0,
                child: GeneratedOnlineWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 214.0,
                height: 44.0,
                child: GeneratedMasterClassWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 349.0,
                child: GeneratedFrame2Widget(),
              ),
              Positioned(
                left: 291.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 349.0,
                child: GeneratedFrame3Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 191.0,
                height: 31.0,
                child: GeneratedFreeonlineclassWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 18.0,
                child: GeneratedFromover80LecturesWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 592.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 134.0,
                child: GeneratedFrame4Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 734.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 134.0,
                child: GeneratedFrame5Widget(),
              )
            ]),
      ),
    ));
  }
}
