import 'package:flutter/material.dart';
import 'package:flutterapp/figmaflutterapp/generateddribbbleshothd1widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/figmaflutterapp/generateddribbbleshothd1widget/generated/GeneratedDoodle51Widget.dart';
import 'package:flutterapp/figmaflutterapp/generateddribbbleshothd1widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/figmaflutterapp/generateddribbbleshothd1widget/generated/GeneratedHome1Widget.dart';
import 'package:flutterapp/figmaflutterapp/generateddribbbleshothd1widget/generated/GeneratedDoodle21Widget.dart';
import 'package:flutterapp/figmaflutterapp/generateddribbbleshothd1widget/generated/GeneratedDoodle41Widget.dart';
import 'package:flutterapp/figmaflutterapp/generateddribbbleshothd1widget/generated/GeneratedDoodle31Widget.dart';
import 'package:flutterapp/figmaflutterapp/generateddribbbleshothd1widget/generated/GeneratedDetails1Widget.dart';

/* Frame Dribbble shot HD - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDribbbleshotHD1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 800.0,
        height: 600.0,
        child: Stack(fit: StackFit.expand, alignment: Alignment.center,
            // overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 217, 223, 232),
                ),
              ),
              Positioned(
                left: 132.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 457.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 397.0,
                top: 127.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 457.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 114.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 508.0,
                child: GeneratedHome1Widget(),
              ),
              Positioned(
                left: 400.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 508.0,
                child: GeneratedDetails1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 444.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 155.0,
                child: GeneratedDoodle41Widget(),
              ),
              Positioned(
                left: 322.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 155.0,
                child: GeneratedDoodle51Widget(),
              ),
              Positioned(
                left: 645.0,
                top: 429.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 155.0,
                child: GeneratedDoodle31Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 155.0,
                child: GeneratedDoodle21Widget(),
              )
            ]),
      ),
    ));
  }
}
